# database configurations
db:
  host : "localhost"
  port : "3306"
  user : "pardhu"
  password : "5915"
  database : "mysql"

#http connector configurations
http:
  host : "0.0.0.0"
  port : "8081"
  
deployed-environment : "dev-environment"
App-name : "customer_management"